### PR TITLE
Fix project dependencies so test can be run

### PR DESCRIPTION
**Pull request by purbon**
Simple fix on the dependencies, so test can actually be run in this filter.

### CODE REVIEW

**Comment by jsvd** [comment]
```
% git clone https://github.com/logstash-plugins/logstash-filter-metricize
Cloning into 'logstash-filter-metricize'...
remote: Counting objects: 66, done.
remote: Total 66 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (66/66), done.
Checking connectivity... done.
% cd logstash-filter-metricize
% bundle install && bundle exec rspec
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Installing rake 10.4.2
Using gem_publisher 1.5.0
Using bundler 1.8.0
Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
bundle install  25.34s user 1.38s system 169% cpu 15.795 total
Gem::LoadError: rspec-core is not part of the bundle. Add it to Gemfile.
     gem at /Users/joaoduarte/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.8.0/lib/bundler/rubygems_integration.rb:256
         at /Users/joaoduarte/.rvm/gems/jruby-1.7.19/bin/rspec:22
    eval at org/jruby/RubyKernel.java:1107
  (root) at /Users/joaoduarte/.rvm/gems/jruby-1.7.19/bin/jruby_executable_hooks:15
bundle exec rspec  17.54s user 1.07s system 227% cpu 8.178 total
```

**Comment by purbon** [comment]
@jsvd I guess you tested master, not this pr ... this is exactly that I've fix in this pr. ... but testing again to be sure.

**Comment by jsvd** [comment]
nevermind, works, LGTM

**Comment by purbon** [comment]
;-)

**Pull request closed without merging**
